apiVersion : apps/v1
kind: Deployment
metadata:
  name: springyaml
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springyaml
  template:
    metadata:
      labels:
        app: springyaml
    spec:
      containers:
        - name: springyaml
          image:  mypractice.azurecr.io/springyaml
          ports:
          - containerPort: 80
